version: '3.3'

services:
  traefik:
    image: traefik:v2.9
    restart: always
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=admin@lucky-safe-bream.ngrok-free.app
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt_data:/letsencrypt

  frontend:
    image: ghcr.io/dennis-off/svhm-app:${GIT_COMMIT_HASH:-latest}
    restart: unless-stopped
    environment:
      APP_ENV_PREFIX: SVHMAPP
      SVHMAPP_WEBSITE_URL: http://localhost:3000
      SVHMAPP_PORT: 3000
      SVHMAPP_NEXT_PUBLIC_API_URL: https://api.lucky-safe-bream.ngrok-free.app
      SVHMAPP_PREVIEW_SECRET: +Powell12
      NODE_ENV: production
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`lucky-safe-bream.ngrok-free.app`) || Host(`www.lucky-safe-bream.ngrok-free.app`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=myresolver
      - traefik.http.routers.frontend.middlewares=www
      - traefik.http.middlewares.www.redirectregex.regex=^https://www.lucky-safe-bream.ngrok-free.app/(.*)
      - traefik.http.middlewares.www.redirectregex.replacement=https://lucky-safe-bream.ngrok-free.app/$$1
      - traefik.http.middlewares.www.redirectregex.permanent=true
  
  backend:
    image: ghcr.io/dennis-off/svhm-strapi:${GIT_COMMIT_HASH:-latest}
    restart: unless-stopped
    volumes:
      - strapi_data:/app/public/uploads 
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_NAME: svhm
      DATABASE_USERNAME: svhm
      DATABASE_PORT: 5432
      APP_KEYS: jP8pb1lYsAhnmURarewxhA==,34xnLMYHY5jiU7ONTstTqQ==
      API_TOKEN_SALT=: svhm
      JWT_SECRET: svhm
      ADMIN_JWT_SECRET: svhm
      DATABASE_PASSWORD_FILE: /run/secrets/db-password
      STRAPI_ADMIN_CLIENT_URL: https://lucky-safe-bream.ngrok-free.app
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: +Powell12
      NODE_ENV: production
    secrets:
      - db-password
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`lucky-safe-bream.ngrok-free.app/api`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=myresolver
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: svhm
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: svhm
    volumes:
      - db_data:/var/lib/postgresql/data
    secrets:
      - db-password
    labels:
      - traefik.enable=false

volumes:
  strapi_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/strapi_data
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/db_data
  letsencrypt_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/letsencrypt_data

secrets:
  db-password:
    external: true