version: '3'
services:
  svhm-app:
    container_name: svhm-app
    image: ghcr.io/dennis-off/svhm-app:latest
    restart: unless-stopped
    env_file: .env
    environment:
      APP_ENV_PREFIX: SVHMAPP
      SVHMAPP_WEBSITE_URL: ${VITE_WEBSITE_URL}
      SVHMAPP_PORT: ${VITE_PORT}
      SVHMAPP_NEXT_PUBLIC_API_URL: http://172.18.0.3:1337
      SVHMAPP_PREVIEW_SECRET: ${VITE_PREVIEW_SECRET}
      NODE_ENV: ${NODE_ENV}
    networks:
      - svhm-strapi
    ports:
      - '8080:8080'
networks:
  svhm-strapi:
    name: svhm-strapi-network
    external: true
