version: '3'
services:
  svhm-strapi:
    container_name: svhm-strapi
    image: ghcr.io/dennis-off/svhm-strapi:${GIT_COMMIT_HASH:-latest}
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: svhm-strapiDB
      DATABASE_NAME: svhm
      DATABASE_USERNAME: svhm
      DATABASE_PORT: 5432
      APP_KEYS: jP8pb1lYsAhnmURarewxhA==,34xnLMYHY5jiU7ONTstTqQ==
      API_TOKEN_SALT=: svhm
      JWT_SECRET: svhm
      ADMIN_JWT_SECRET: svhm
      DATABASE_PASSWORD_FILE: /run/secrets/db-password
      STRAPI_ADMIN_CLIENT_URL: https://lucky-safe-bream.ngrok-free.app
      STRAPI_ADMIN_CLIENT_PREVIEW_SECRET: +Powell12
      NODE_ENV: production
    volumes:
      - strapi-upload:/opt/app/public
    networks:
      - svhm-strapi
    ports:
      - '1337:1337'
    secrets:
      - db-password
    depends_on:
      - svhm-strapiDB
      
  svhm-strapiDB:
    container_name: svhm-strapiDB
    restart: unless-stopped
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: svhm
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_DB: svhm
    volumes:
      - db-data:/var/lib/postgresql/data/ #using a volume
    networks:
      - svhm-strapi
    ports:
      - '5432:5432'
    secrets:
      - db-password

  #svhm-strapiAdminer:
  #  container_name: svhm-strapiAdminer
  #  image: adminer
  #  restart: unless-stopped
  #  networks:
  #    - svhm-strapi
  #  ports:
  #    - '9090:9090'
  #  environment:
  #    - ADMINER_DEFAULT_SERVER=svhm-strapiDB
  #  depends_on:
  #    - svhm-strapiDB

  svhm-app:
    container_name: svhm-app
    image: ghcr.io/dennis-off/svhm-app:${GIT_COMMIT_HASH:-latest}
    restart: unless-stopped
    environment:
      APP_ENV_PREFIX: SVHMAPP
      SVHMAPP_WEBSITE_URL: http://localhost:3000
      SVHMAPP_PORT: 3000
      SVHMAPP_NEXT_PUBLIC_API_URL: https://lucky-safe-bream.ngrok-free.app
      SVHMAPP_PREVIEW_SECRET_FILE: /run/secrets/db-password
      NODE_ENV: production
    networks:
      - svhm-strapi
    ports:
      - '8080:8080'
    secrets:
      - db-password
      
volumes:
  strapi-upload:
  db-data:

networks:
  svhm-strapi:
    name: svhm-strapi-network
    driver: overlay

secrets:
  db-password:
    external: true