version: '3'
name: 'nginx_react_typescript_docker'

services:
  app:
    image: svhm-local3
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - "./nginx/nginx.conf://etc/nginx/nginx.conf:ro"
    networks:
      - svhm-app

networks:
  svhm-app:
    name: svhm-strapi-network
    external: true