name: App dockerize

on:
  push:
    branches: ["main"]
    #paths:
    #  - "svhm-app/version.cfg"
  pull_request:
    branches: ["main"]
    paths:
      - "svhm-app/version.cfg"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image
        run: |
          cd svhm-app
          docker buildx create --use --name multiarch-builder
          docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/${{ github.repository_owner }}/svhm-app:latest --push .
