name: App dockerize

on:
  push:
    branches: [ "main" ]
    paths:
      - "svhm-app/version.cfg"
  pull_request:
    branches: [ "main" ]
    paths:
    - "svhm-app/version.cfg"
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build the Docker image
      run: |
        cd svhm-app
        docker build -t svhm-app:latest .
        docker tag svhm-app:latest ghcr.io/${{ github.repository_owner }}/svhm-app:latest

    - name: Push the Docker image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/svhm-app:latest
