name: Strapi dockerize

on:
  push:
    branches: ["main"]
    #paths:
    #  - "svhm-strapi/version.cfg"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/svhm-strapi:latest
            ghcr.io/${{ github.repository_owner }}/svhm-strapi:${{ github.sha }}
          context: ./svhm-strapi
          file: ./svhm-strapi/Dockerfile.prod
          build-args: |
            NODE_ENV=production
